# Generated by Django 4.1.6 on 2023-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_featured_alter_product_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="featured",
            field=models.BooleanField(),
        ),
    ]
